name: Perform Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to release (major.minor.patch)
        required: true

jobs:
  perform-release:
    name: Perform Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Tag current version
        run: git tag ${{ github.event.inputs.version }} && git push --tags
